"""
Generate supabase/import-partners-rentals.sql from the Bali transport business Excel export.

Keeps only Car Rentals and Scooter Rentals (no Mechanics, no Tow Services),
dedupes within the file (normalized name + phone) and against known existing
partner names, then emits INSERT ... ON CONFLICT (id) DO NOTHING statements.

Usage:  python scripts/generate_partner_import.py <path-to-xlsx>
"""
import hashlib
import re
import sys
import zipfile
from xml.etree import ElementTree as ET

M = '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'
KEEP_CATEGORIES = {'Car Rentals', 'Scooter Rentals'}
# Existing partner names in the live DB (do not re-import)
EXISTING_NAMES = {'budi dharma trans', 'blue swan bali', 'bali adventure tours'}
ADMIN_USER_ID = '6a0947b7b4a68dcdea755505'
ADMIN_EMAIL = 'arrafahvega@gmail.com'
SORT_ORDER_START = 100


def read_rows(path):
    z = zipfile.ZipFile(path)
    shared = [''.join(t.text or '' for t in si.iter(M + 't'))
              for si in ET.fromstring(z.read('xl/sharedStrings.xml')).findall(M + 'si')]
    ws = ET.fromstring(z.read('xl/worksheets/sheet1.xml'))
    rows = []
    for row in ws.iter(M + 'row'):
        cells = {}
        for c in row.findall(M + 'c'):
            col = re.match(r'[A-Z]+', c.get('r')).group()
            v, is_ = c.find(M + 'v'), c.find(M + 'is')
            val = ''
            if c.get('t') == 's' and v is not None:
                val = shared[int(v.text)]
            elif c.get('t') == 'inlineStr' and is_ is not None:
                val = ''.join(t.text or '' for t in is_.iter(M + 't'))
            elif v is not None:
                val = v.text
            cells[col] = (val or '').strip()
        rows.append(cells)
    return rows


def norm_name(name):
    return re.sub(r'[^a-z0-9]', '', name.lower())


def norm_phone(phone):
    return re.sub(r'\D', '', phone or '')


def sql(s):
    return "'" + (s or '').replace("'", "''") + "'"


def make_id(name):
    return hashlib.md5(norm_name(name).encode()).hexdigest()[:24]


def main():
    xlsx = sys.argv[1] if len(sys.argv) > 1 else \
        r'C:\Users\user\Downloads\Bali_Transport_Vehicle_Business_Data.xlsx'
    rows = read_rows(xlsx)
    header, data = rows[0], rows[1:]

    seen, skipped_dup, skipped_cat, out = set(), 0, 0, []
    for c in data:
        name = c.get('A', '')
        if not name:
            continue
        category = c.get('J', '')
        if category not in KEEP_CATEGORIES:
            skipped_cat += 1
            continue
        phone = norm_phone(c.get('I', ''))
        key = (norm_name(name), phone)
        if norm_name(name) in EXISTING_NAMES or key in seen:
            skipped_dup += 1
            continue
        seen.add(key)

        rating = float(c.get('B') or 0)
        reviews = int(float(c.get('C') or 0))
        street, city = c.get('D', ''), c.get('E', '')
        desc = f"{category.replace(' Rentals', ' Rental')} in {city} · \u2b50 {rating:g} ({reviews} reviews)"
        out.append({
            'name': name, 'category': category, 'address': street, 'city': city,
            'maps_url': c.get('K', ''), 'website_url': c.get('H', ''),
            'pic_phone': phone, 'rating': rating, 'reviews_count': reviews,
            'description': desc,
        })

    out.sort(key=lambda r: (r['category'], r['city'].lower(), r['name'].lower()))
    lines = [
        '-- ============================================================================',
        '-- Partner import: Car Rentals + Scooter Rentals from Excel business export.',
        '-- Admin-only partners: publish_on_website = false (not shown publicly).',
        '-- Generated by scripts/generate_partner_import.py — do not edit by hand.',
        '-- ============================================================================',
        'INSERT INTO public.partners (name, category, address, city, maps_url, website_url, pic_phone, rating, reviews_count, description, notes, is_active, publish_on_website, sort_order, id, created_date, updated_date, created_by_id, created_by, is_sample)',
        'VALUES',
    ]
    vals = []
    for i, p in enumerate(out):
        vals.append(
            f"({sql(p['name'])},{sql(p['category'])},{sql(p['address'])},{sql(p['city'])},"
            f"{sql(p['maps_url'])},{sql(p['website_url'])},{sql(p['pic_phone'])},"
            f"{p['rating']:g},{p['reviews_count']},{sql(p['description'])},"
            f"{sql('Imported from Bali_Transport_Vehicle_Business_Data.xlsx')},"
            f"'true','false',{SORT_ORDER_START + i},'{make_id(p['name'])}',now(),now(),"
            f"'{ADMIN_USER_ID}',{sql(ADMIN_EMAIL)},'false')"
        )
    lines.append(',\n'.join(vals))
    lines.append('ON CONFLICT (id) DO NOTHING;')
    lines.append('')
    lines.append('-- Verification')
    lines.append("SELECT category, COUNT(*) FROM public.partners WHERE category IS NOT NULL GROUP BY category;")

    dest = 'supabase/import-partners-rentals.sql'
    with open(dest, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f'wrote {dest}: {len(out)} partners '
          f'(skipped {skipped_cat} non-rental rows, {skipped_dup} duplicates)')


if __name__ == '__main__':
    main()
